--ADDITIONAL SELECT ----



--1번-------
SELECT STUDENT_NO AS 학번,STUDENT_NAME AS 이름,ENTRANCE_DATE AS 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO ='002'
ORDER BY ENTRANCE_DATE;


---2번----
SELECT PROFESSOR_NAME,PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

--3번-----
SELECT PROFESSOR_NAME AS "교수이름" ,PROFESSOR_SSN AS "나이"
FROM TB_PROFESSOR
WHERE ;

--교수 여성 남성--
SELECT PROFESSOR_NAME,DECODE(SUBSTR(PROFESSOR_SSN,8,1),'1','남성','2','여성')AS "성별" FROM TB_PROFESSOR;