---SELECT 예제 다품----
----BASIC SELECT-----

----1번-----
SELECT * FROM TB_DEPARTMENT;
SELECT DEPARTMENT_NAME AS "학과명",CATEGORY AS "계열" FROM TB_DEPARTMENT;

----2번-------
SELECT DEPARTMENT_NAME||' 의 정원은', CAPACITY||'명 입니다.'AS "학과별 정원" FROM TB_DEPARTMENT;

---3번----여성인거 따오기가 어려워서 그냥 -2 포함
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO ='001' AND ABSENCE_YN ='Y'AND STUDENT_SSN LIKE '%-2%';

---3-1번-------
SELECT DEPARTMENT_NO,STUDENT_NAME ,ABSENCE_YN,STUDENT_SSN
FROM TB_STUDENT
WHERE SUBSTR (STUDENT_SSN,8,1)='2'
AND DEPARTMENT_NO ='001' AND ABSENCE_YN ='Y' ;

---4번----
SELECT  STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN('A513079' ,'A513090','A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NAME DESC;

----5번-----
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

----6번----
SELECT * FROM TB_PROFESSOR;
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

----7번 -----
SELECT * FROM TB_STUDENT;
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

----8번------
SELECT * FROM TB_CLASS;
SELECT PREATTENDING_CLASS_NO AS "CLASS_NO"
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-----9번-------
SELECT *FROM TB_DEPARTMENT;
SELECT DISTINCT CATEGORY FROM TB_DEPARTMENT;

-----10번--------
SELECT STUDENT_NO,STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE '%전주%'AND ABSENCE_YN ='N'AND ENTRANCE_DATE BETWEEN '2002-01-01' AND '2002-12-31';
